### ISSUE TITLE
Can't install dependencies.

### ISSUE THREAD

**Issue by paulioceano** [lagadic/demo_pioneer#4]
Hi! I've been following the ROS tutorial to install V-Rep in Ubuntu 16.04.

In my terminal, when I run: rosdep install demo_pioneer

I get the following error:
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
demo_pioneer: Cannot locate rosdep definition for [camera1394]

What I'm I doing wrong? or what else I need to run before rosdep install demo_pioneer.

thank you!

**Comment by jokla** [comment]
Hi, do you want to control the real robot or the simulated robot in V-Rep?

You need camera1394 only if you are using a real camera (FireWire). If you use the simulated robot in V-Rep, I would say it is not necessary to run `rosdep install demo_pioneer` . You will not need the `rosaria stack` neither.

Try to install [vision_visp]( http://wiki.ros.org/vision_visp), clone `demo_pionner` in your src folder, and build the package with catkin_make. 

Let me know if this solve your problem

**Comment by paulioceano** [comment]
Hi!

For now I just need the simulated robot... Maybe in september I'll have to control the real one in the lab.

I'll try your solution this afternoon after work. I'll let you know if it works. Thank you!

**Comment by fspindle** [comment]
Your error comes from [camera1394](http://wiki.ros.org/camera1394) run dependency that is not packaged for jade and kinetic and that is only useful as said by @jokla if you want to use [demo-visual-servo-pioneer-pan.launch](https://github.com/lagadic/demo_pioneer/blob/master/launch/demo-visual-servo-pioneer-pan.launch|) with a Pioneer equipped with a firewire camera.

I will simply remove the dependency that is not really mandatory to use this package.

To use the launch file as is on a real robot, users have to install  [camera1394](http://wiki.ros.org/camera1394) and [rosaria](http://wiki.ros.org/ROSARIA) from source if they are not packaged for the given distro.
