### ISSUE TITLE
How to invert the velocity command before publishing?

### ISSUE THREAD

**Issue by Gowresh7** [lagadic/demo_pioneer#6]
I want to mount the camera at the rear of the robot. So that the robot will move backwards towards the QR code. How to invert the published velocities to achieve this?

**Comment by fspindle** [comment]
You need to modify the `cVe` matrix that allows to transform a velocity twist vector expressed in the camera frame into the robot end-effector frame. 

The model of your setup is the following: 
![model-pioneer-rear-camera](https://user-images.githubusercontent.com/1412746/60573514-170ee800-9d78-11e9-9b5b-359c376b49c1.png)

If I consider [visual_servo_pioneer.cpp](https://github.com/lagadic/demo_pioneer/blob/master/src/visual_servo_pioneer.cpp) this has to be done arround line [111](https://github.com/lagadic/demo_pioneer/blob/master/src/visual_servo_pioneer.cpp#L111) and line [197](https://github.com/lagadic/demo_pioneer/blob/master/src/visual_servo_pioneer.cpp#L197), where: 
```
task.set_cVe( cVe );
```
should be replaced by:
```
vpRotationMatrix cRe { 0, 0, -1, 0, -1, 0, -1, 0, 0 };
double dy = 0.01, dz = 0.20; // need to be adapted
vpTranslationVector cte(0, dy, -dz);
vpHomogeneousMatrix cMe(cte, cRe);
cVe.buildFrom(cMe);
task.set_cVe( cVe );
```

**Comment by Gowresh7** [comment]
Thank you. Will try it out and revert back..!!

**Comment by Gowresh7** [comment]
Fabien,
It works excellent..!! But its just that it is moving very slowly. How do I increase the speed..??

**Comment by fspindle** [comment]
You need to tune the values of `lambda_adapt` that corresponds to the adptive gain implemented in [vpAdaptiveGain](https://visp-doc.inria.fr/doxygen/visp-daily/classvpAdaptiveGain.html#a4309b55b8dc57a29298d871ef0005282).

**Comment by Gowresh7** [comment]
How exactly to tune the values of lambda_adapt?
