### ISSUE TITLE
What should I do to differentiate between QR codes

### ISSUE THREAD

**Issue by Gowresh7** [lagadic/demo_pioneer#8]
I want the camera to detect only a specific QR code.  If I show it another code, it should not proceed.
What are the parameters I need to change?

**Comment by fspindle** [comment]
You need to modify the `visp_auto_tracker` source code [around here](https://github.com/lagadic/vision_visp/blob/master/visp_auto_tracker/flashcode_mbt/detectors/qrcode/detector.cpp#L33) to test if the QRcode `message_`  corresponds to the one you want to track.

**Comment by Gowresh7** [comment]
Did it..!! Thanks again..!! It was the topic code_message.
